### PR TITLE
Fix multibyte string conversion

### LINKED ISSUE #237: Recent change in #234 munges utf8mb4 bytes (like 🧮)
[This commit](https://github.com/tijsverkoyen/CssToInlineStyles/commit/4348a3a06651827a27d989ad1d13efec6bb49b19) changing from `mb_convert_encoding()` to `mb_encode_numericentity()` introduces an issue that munges utf8mb4 bytes in a string.

This appears to affect any 4-byte character, like 🧮, but not fewer bytes like ✈️.

The output from `$cssToInlineStyles->convert()` ends up looking like `ð§`.

We had to pin back to 2.2.4 in Composer to resolve an issue with outgoing mail that runs through this function.

### PR DESCRIPTION
**Pull request by Ugoku**
Fixes #237

### CODE REVIEW

File: tests/CssToInlineStylesTest.php [hunk 1]
```diff
@@ -267,6 +267,54 @@ public function testSelfClosingTags()
...
+    {
+        $html = '\u{10FFFF}';
+        $css = '';
+        $expected = "<p>{$html}</p>";
+        $this->assertCorrectConversion($expected, $html, $css);
+    }
+
+    public function testConversionIllegalCodepoint()
+    {
+        $html = '\u{110000}';
```
Comment (stof) [inline tests/CssToInlineStylesTest.php:304]: shouldn't this use a double-quoted string if you intent to use U+110000 ? Your current code does not use an escape sequence here. It creates a pure-ASCII HTML

Comment (Ugoku) [reply tests/CssToInlineStylesTest.php:304]: 🤦‍♂️ you're right, will fix!
